### ISSUE TITLE
Rain example gives an error on aframe 1.1.0 to 1.4.0

### ISSUE THREAD

**Issue by vincentfretin** [IdeaSpaceVR/aframe-particle-system-component#70]
With latest master (Feb 25, 2022), the rain example gives an error on aframe 1.1.0 to 1.3.0, also on 1.4.0 with #68
```
Uncaught (in promise) TypeError: e.size.map is not a function
    at n.initParticleSystem (aframe-particle-system-component.min.js:1:4955)
    at n.update (aframe-particle-system-component.min.js:1:3088)
    at n.initComponent (component.js:333:10)
    at n.updateProperties (component.js:305:12)
    at e.exports.Component (component.js:81:8)
    at new n (component.js:665:15)
    at d.initComponent (a-entity.js:319:17)
    at d.updateComponent (a-entity.js:471:10)
    at d.updateComponents (a-entity.js:442:12)
    at a-entity.js:243:12
```

**Comment by vincentfretin** [comment]
This is fixed by #71

**Comment by diarmidmackenzie** [comment]
Fix also available at: https://www.npmjs.com/package/@c-frame/aframe-particle-system-component
